### ISSUE TITLE
version 0.3.0 generates invalid code.

### ISSUE THREAD

**Issue by SuperDoxin** [D-Programming-Language/dub#765]
given this grammar:

    assemblyFile:
    list <- line+ EOF
    line <- :WS? comment / instruction
    comment <- :';' ~((!'\n' .)*) EOL / EOL
    label_list <- (label :WS?)*
    label <- ~(!opcode ([a-zA-Z_] [a-zA-Z0-9_]*))
    operation <- opcode :'.' modifier / opcode
    opcode <- 'DAT' / 'MOV' / 'ADD' / 'SUB' / 'MUL' / 'DIV' / 'MOD' / 'JMP' /
             'JMZ' / 'JMN' / 'DJN' / 'CMP' / 'SLT' / 'SPL' / 'SNE' / 'SEQ' / 'ORG' / 'EQU' / 
             'END'
    modifier <- 'AB' / 'BA' / 'A' / 'B' / 'F' / 'X' / 'I' / eps
    mode <- '#' / '$' / '@' / '<' / '>' / '{' / '}' / '*' / eps
    expr <- '(' expr ')' / term '%' expr / term '/' expr / term '*' expr / term '-' expr /
           term '+' expr / term
    term <- label / number / expr
    number <- whole_number / signed_integer
    signed_integer <~ '+' whole_number / '-' whole_number
    whole_number <~ [0-9]+
    WS <- ' '+
    EOL <- :'\n' / EOF
    EOF <- !.
    
    instruction <- label_list :WS? operation :WS? mode :WS? expr :WS? ',' :WS? mode :WS? expr :WS? comment / 
                   label_list :WS? operation :WS? mode :WS? expr :WS? comment

it generates unreachable code, which is a warning, which under dub defaults to an error.

when you then disable generating errors for warnings it fails to link:

    Performing "debug" build using dmd for x86_64.
    pegged 0.3.0: target for configuration "library" is up to date.
    redparser ~master: building configuration "application"...
    source/parser.d-mixin-189(654,133): Warning: statement is not reachable
    Linking...
    .dub/build/application-debug-linux.posix-x86_64-dmd_2069-7BC6E58A413187F61AFD3B46A6522C12/redparser.o: In function `_D6pegged7grammar44__T7grammarVE6pegged7grammar11Memoizationi1Z7grammarFAyaZ21leftRecursionStoppersMFNaZAAya':
    /home/lieuwe/Desktop/dlang/redparser/../../../.dub/packages/pegged-0.3.0/pegged/grammar.d:115: undefined reference to `_D6pegged13introspection8ruleInfoFNaS6pegged3peg9ParseTreeZHAyaS6pegged13introspection8RuleInfo'
    .dub/build/application-debug-linux.posix-x86_64-dmd_2069-7BC6E58A413187F61AFD3B46A6522C12/redparser.o:(.data._D41TypeInfo_S6pegged13introspection8RuleInfo6__initZ+0x30): undefined reference to `_D6pegged13introspection8RuleInfo9__xtoHashFNbNeKxS6pegged13introspection8RuleInfoZm'
    .dub/build/application-debug-linux.posix-x86_64-dmd_2069-7BC6E58A413187F61AFD3B46A6522C12/redparser.o:(.data._D41TypeInfo_S6pegged13introspection8RuleInfo6__initZ+0x38): undefined reference to `_D6pegged13introspection8RuleInfo11__xopEqualsFKxS6pegged13introspection8RuleInfoKxS6pegged13introspection8RuleInfoZb'
    collect2: error: ld returned 1 exit status
    --- errorlevel 1
    dmd failed with exit code 1.

now I'm sure I did something wrong here, but I can't figure out what's going on inside that mixin.

NOTE: this exact same grammar *did* work using 0.2.1

**Comment by SuperDoxin** [comment]
oops I opened an issue on the wrong project. apologies.
